image: node:14-buster

stages:
  - build
  - release

test:
  stage: build
  script:
    - yarn
    - yarn run test:ci
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml
      junit: junit.xml

checks:
  stage: build
  script:
    - yarn
    - yarn run check

build:
  stage: build
  script:
    - yarn
    - yarn run build
  artifacts:
    paths:
      - dist

release:
  stage: release
  script:
    - mkdir $HOME/.ssh
    - cp "$DEPLOY_KEY" $HOME/.ssh/id_rsa
    - chmod g=,o= $HOME/.ssh/id_rsa
    - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - git remote set-url --push origin git@gitlab.com:$CI_PROJECT_PATH.git
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"
    - yarn
    - yarn release
    - git push --follow-tags origin master
  only:
    - main
  when: manual
  allow_failure: false

publish:
  stage: release
  script:
    - 'echo //gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN} >> ~/.npmrc'
    - yarn
    - yarn publish
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TAG
