image: node:14-buster

stages:
  - build
  - publish

test:
  stage: build
  script:
    - yarn
    - yarn run test:ci
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml
      junit: junit.xml

checks:
  stage: build
  script:
    - yarn
    - yarn run check

build:
  stage: build
  script:
    - yarn
    - yarn run build
  artifacts:
    paths:
      - dist

publish:
  stage: publish
  script:
    - 'echo @emigrad:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/ >> ~/.npmrc'
    - 'echo //gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN} >> ~/.npmrc'
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"
    - yarn
    - yarn release
  only:
    - main
  when: manual
  allow_failure: false